// Mock data for the application

// Product data with merchant details
export const products = [
  {
    id: 1,
    name: "Latest Smartphone",
    description: "High performance smartphone with advanced camera",
    price: 799.99,
    rating: 5,
    category: "electronics",
    merchant: "TechTrend Innovations",
    merch_zipcode: "10001",
  },
  {
    id: 2,
    name: "Premium Laptop",
    description: "High-performance laptop with 16GB RAM and 512GB SSD",
    price: 1299.99,
    rating: 5,
    category: "electronics",
    merchant: "TechTrend Innovations",
    merch_zipcode: "10001",
  },
  {
    id: 3,
    name: "Wireless Headphones",
    description: "Premium noise-cancelling wireless headphones",
    price: 299.99,
    rating: 4,
    category: "electronics",
    merchant: "SoundWave Store",
    merch_zipcode: "90210",
  },
  {
    id: 4,
    name: "Smartwatch",
    description: "Advanced health monitoring and fitness tracking",
    price: 249.99,
    rating: 4,
    category: "electronics",
    merchant: "TechTrend Innovations",
    merch_zipcode: "10001",
  },
  {
    id: 5,
    name: "Gaming Console",
    description: "Next-generation gaming with realistic graphics",
    price: 499.99,
    rating: 5,
    category: "electronics",
    merchant: "GameZone Retail",
    merch_zipcode: "60601",
  },
  {
    id: 6,
    name: "Professional Camera",
    description: "High-resolution DSLR camera with multiple lenses",
    price: 1899.99,
    rating: 5,
    category: "electronics",
    merchant: "PhotoPro Shop",
    merch_zipcode: "33101",
  },
  {
    id: 7,
    name: "Designer T-Shirt",
    description: "Premium cotton t-shirt with modern design",
    price: 39.99,
    rating: 4,
    category: "clothing",
    merchant: "FashionHub",
    merch_zipcode: "75201",
  },
  {
    id: 8,
    name: "Programming Book",
    description: "Complete guide to modern web development",
    price: 49.99,
    rating: 5,
    category: "books",
    merchant: "BookHaven",
    merch_zipcode: "94105",
  },
  {
    id: 9,
    name: "Coffee Maker",
    description: "Automatic coffee maker with built-in grinder",
    price: 199.99,
    rating: 4,
    category: "home",
    merchant: "HomeEssentials",
    merch_zipcode: "98101",
  },
  {
    id: 10,
    name: "Bluetooth Speaker",
    description: "Portable speaker with rich sound and long battery life",
    price: 79.99,
    rating: 4,
    category: "electronics",
    merchant: "SoundWave Store",
    merch_zipcode: "90210",
  },
];

// Purchase data
export const purchases = [
  {
    id: 1,
    name: "Premium Laptop",
    description: "High-performance laptop with 16GB RAM and 512GB SSD",
    amount: 75999,
    date: "15 May 2025",
    status: "Delivered",
    orderId: "#ORD-85967",
    image: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?ixlib=rb-4.0.3&auto=format&fit=crop&w=200&h=200&q=80",
  },
  {
    id: 2,
    name: "Wireless Headphones",
    description: "Premium noise-cancelling wireless headphones",
    amount: 24999,
    date: "10 May 2025",
    status: "Delivered",
    orderId: "#ORD-85920",
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?ixlib=rb-4.0.3&auto=format&fit=crop&w=200&h=200&q=80",
  },
  {
    id: 3,
    name: "Smartwatch",
    description: "Advanced health monitoring and fitness tracking",
    amount: 18999,
    date: "5 May 2025",
    status: "Shipped",
    orderId: "#ORD-85890",
    image: "https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?ixlib=rb-4.0.3&auto=format&fit=crop&w=200&h=200&q=80",
  },
];

// Credit card data
export const creditCard = {
  number: "5340 4991 1190",
  crn: "227869105",
  cvv: "2614",
  bankName: "Indian Bank",
  holderName: "raj",
  creditLimit: 100000,
  cashLimit: 40000,
  expiryDate: "25/04/2027",
};

// User profile data
export const userProfile = {
  username: "raj",
  bankName: "Indian Bank",
  email: "raj@gmail.com",
  mobile: "1234567890",
  address: "Somarampet Bamjepally,Marrthanda",
  dob: "2000",
};